### ISSUE TITLE
NimBLEDevice.h: No such file or directory

### ISSUE THREAD

**Issue by czgab** [formatBCE/ESP32_BLE_presense#16]
I wanted to install this on my M5Stack Atom Lite device alongside the ESPHome Bluetooth proxy Ready-Made Projects, but I get the following error message: `src/esphome/components/esp32_ble_presense/esp32_ble_presense.cpp:9:10: fatal error: NimBLEDevice.h: No such file or directory`

Device: M5Stack Atom Lite
ESPHome version: 2024.7.3 running in Docker on Ubuntu 24.

My Device config:

```
substitutions:
  name: m5stack-atom-lite-a1133c
  friendly_name: Bluetooth Proxy Living Room
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: very_secret

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# ---------------   Format-BLE-Tracker    --------------- 
# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time

# Initializing it:
esp32_ble_presense:
  area: "Living room"
  time_id: homeassistant_time

# MQTT config - required for this component to work:
mqtt:
  broker: 192.168.1.110
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
```

Complete log:
```
INFO ESPHome 2024.7.3
INFO Reading configuration /config/m5stack-atom-lite-a1133c.yaml...
INFO Detected timezone 'Etc/UTC'
INFO Generating C++ source...
INFO Compiling app...
Processing m5stack-atom-lite-a1133c (board: m5stack-atom; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Library Manager: Installing NimBLE-Arduino @ 1.4.2
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: NimBLE-Arduino@1.4.2 has been installed!
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/api_connection.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/api_server.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/list_entities.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/proto.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/api/user_services.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/button/button.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32/core.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble/ble.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble/ble_advertising.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble/ble_uuid.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_client/ble_characteristic.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_client/ble_client_base.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_client/ble_service.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_presense/esp32_ble_presense.o
Compiling .pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
src/esphome/components/esp32_ble_presense/esp32_ble_presense.cpp:9:10: fatal error: NimBLEDevice.h: No such file or directory

**********************************************************************
* Looking for NimBLEDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NimBLEDevice.h"
* Web  > https://registry.platformio.org/search?q=header:NimBLEDevice.h
*
**********************************************************************

 #include <NimBLEDevice.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/m5stack-atom-lite-a1133c/src/esphome/components/esp32_ble_presense/esp32_ble_presense.o] Error 1
========================= [FAILED] Took 22.54 seconds =========================
```
