### ISSUE TITLE
Everything presence One

### ISSUE THREAD

**Issue by lukshan13** [formatBCE/ESP32_BLE_presense#17]
Hi. I've got the Everything Presence One. I've included your instructions into the yaml as follows
```
mqtt:
  broker: homeassistant.local:1883
  username: {username}
  password: {password}
  discovery: true

# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

time:
  - platform: homeassistant
    id: homeassistant_time

# Initializing it:
esp32_ble_presense:
  area: "Living room" # Replace this with your room name
  time_id: homeassistant_time

substitutions:
  name: everything-presence-one-fa2ccc
  friendly_name: Everything Presence One fa2ccc
  
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/everything-presence-one/everything-presence-one-beta.yaml@main
esphome:
  platformio_options:
    lib_deps: h2zero/NimBLE-Arduino@1.4.2
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: {key}


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

However, when i go to install it, I get the following error:

src/esphome/components/esp32_ble_presense/esp32_ble_presense.cpp:9:10: fatal error: NimBLEDevice.h: No such file or directory

As you can see, I've tried to include the library but still can't seem to get past it. Do you have any direction? Thanks
