### ISSUE TITLE
Compilation issue, include-file Arduino.h file not found. Perhaps related to use of framework esp-idf?

### ISSUE THREAD

**Issue by evoncken** [formatBCE/ESP32_BLE_presense#4]
After adding ble-node.h to my ESPhome device config, and cleaning the build files, I ran into the following build error:

```
Compiling .pioenvs/airco-woonkamer/app_update/esp_ota_ops.o
In file included from src/main.cpp:54:
src/ble-node.h:11:10: fatal error: Arduino.h: No such file or directory

*****************************************************************
* Looking for Arduino.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Arduino.h"
* Web  > https://registry.platformio.org/search?q=header:Arduino.h
*
*****************************************************************

 #include <Arduino.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pioenvs/airco-woonkamer/src/main.o] Error 1
```

The esphome section is configured as follows:

```
esphome:
  name: "${devicename}"
  name_add_mac_suffix: false   ## if 'false' use different names/hostnames for each device!
  comment: "${long_devicename} ${pcb_version}"
  project:
    name: "esphome.pana-climate"
    version: "${pcb_version}"
  # Format-BLE-Tracker
  includes:
    - ble-node.h
  libraries:
    - "h2zero/NimBLE-Arduino"
```

I'm using the 'esp-idf' framework. Could that be the issue? Perhaps a dependency I need to install?

```
esp32:
  board: mhetesp32minikit
  framework:
    type: esp-idf
    version: recommended
```

Thank you ;-)
