### ISSUE TITLE
adding to NSPanel_HA_Blueprint

### ISSUE THREAD

**Issue by SJoWie80** [formatBCE/ESP32_BLE_presense#8]
Hello,

can this be compatible with NSpanel. specific:
https://github.com/Blackymas/NSPanel_HA_Blueprint

when i add the following:
```

# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main
# Initializing it:
esp32_ble_presense:
  area: "Living room" # Replace this with your room name
# MQTT config - required for this component to work:
mqtt:
  broker: 192.168.0.1 # TODO replace with your MQTT server IP
  username: !secret mqtt_user # TODO replace with your MQTT user or remove
  password: !secret mqtt_password # TODO replace with your MQTT password or remove
  discovery: true
# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time
```

i get the error:

INFO ESPHome 2024.7.2
INFO Reading configuration /config/esphome/nspanel-woonkamer.yaml...
Failed config
nspanel_ha_blueprint: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:136]
  Component not found: nspanel_ha_blueprint.

the whole esphome config is:
```
esphome:
  name: nspanel-woonkamer
  friendly_name: NSpanel Woonkamer

esp32:
  board: esp32dev
  framework:
    type: esp-idf

substitutions:
  # Settings - Editable values
  device_name: "nspanel woonkamer"
  friendly_name: "NSpanel woonkamer"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.101.102:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
api:
  encryption:
    key: !secret esphome_encryption_key

# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

# Initializing it:
esp32_ble_presense:
  area: "Living room" # Replace this with your room name

# MQTT config - required for this component to work:
mqtt:
  broker: 192.168.101.102 # TODO replace with your MQTT server IP
  username: !secret mqtt_user # TODO replace with your MQTT user or remove
  password: !secret mqtt_password # TODO replace with your MQTT password or remove
  discovery: true

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time




```

**Comment by formatBCE** [comment]
Your error indicates that blueprint repo not found. Nothing to do with
current repository.

However, I'm afraid our repo doesn't work with esp-idf framework so far...
BR
Andrii Mitnovych

**Comment by SJoWie80** [comment]
without the code below it finds the repo just fine when i add the code below it does not work and get that error.

```
# Adding external component to build:
external_components:
  source: github://formatBCE/ESP32_BLE_presense@main

# Initializing it:
esp32_ble_presense:
  area: "Living room" # Replace this with your room name

# MQTT config - required for this component to work:
mqtt:
  broker: 192.168.0.1 # TODO replace with your MQTT server IP
  username: !secret mqtt_user # TODO replace with your MQTT user or remove
  password: !secret mqtt_password # TODO replace with your MQTT password or remove
  discovery: true

# System time config - required for precise timestamps, used in integration:
time:
  - platform: homeassistant
    id: homeassistant_time
```
